### ISSUE TITLE
Redirect from old website URL not working

### ISSUE THREAD

**Issue by LoLei** [goharbor/goharbor.github.io#1]
https://vmware.github.io/harbor

This old website URL redirects to https://vmware.github.io, but it is displayed as a blank page, with only the header visible. Reloading once again displays https://vmware.github.io correctly.

Ideally IMO, it should redirect directly to https://goharbor.io/ anyway.

**Comment by jonasrosland** [comment]
Hi @LoLei, thanks for reaching out. We're aware of the issue and will look into it.

**Comment by jonasrosland** [comment]
@LoLei, this has been corrected by @tomichal:
https://github.com/vmware/vmware.github.io/commit/1fd25942561b5b2c061e818cc31b17cbb3121be7

https://vmware.github.io/harbor now redirects to https://goharbor.io

Thank you for reporting this!
