### ISSUE TITLE
Web updates for CNCF hosting

### ISSUE THREAD

**Issue by dankohn** [goharbor/goharbor.github.io#2]
Could you please update the website to meet https://github.com/cncf/foundation/blob/master/website-guidelines.md

In particular:
1. Please change copyright from VMware to "Project Harbor authors"
2. Fix the links under Getting Started to point to the new repo locations.
3. Replace the logos with the new ones from https://github.com/cncf/artwork/ that don't have the tm.

Please note that this isn't life-or-death. It's fine to take a few weeks.

**Comment by jonasrosland** [comment]
Hi @dankohn, thank you for reaching out. We'll take care of this as soon as possible.

**Comment by ghost** [comment]
Completed @dankohn; many thanks to @jonasrosland for taking care of the changes.

**Comment by dankohn** [comment]
Thanks, but could you please also update the GitHub links in the footer.

**Comment by ghost** [comment]
Apologize for the oversight @dankohn. I just updated the footer links across the site.

**Comment by dankohn** [comment]
Thanks. The other 3 links under Getting Started at the bottom also point to the obsolete vmware repos.

**Comment by ghost** [comment]
Should be fixed when we merge https://github.com/goharbor/blog/pull/6.
